### ISSUE TITLE
No root detected using

### ISSUE THREAD

**Issue by HpNoTiQ56** [yuanwofei/resources#1]
Hi,
I'm using your app in KSU (using susfs ) and your app can't detect root and thus can't emulate card. Other root apps works fine : could you change the root status check?

https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android14-5.15?ref_type=heads

**Comment by HpNoTiQ56** [comment]
https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android14-5.15?ref_type=heads

**Comment by yuanwofei** [comment]
Can you record a video and send it to me to see the effect? Also, do you
mean KernelSU when you say KSU? KernelSU itself requires manual granting of
root permissions in the KernelSU app.

HpNoTiQ ***@***.***> 于2024年11月7日周四 04:40写道：

**Comment by HpNoTiQ56** [comment]
Root permission is already added. Nothing more in logs.
https://github.com/user-attachments/assets/f69c07f4-5986-4a78-9e93-22c4c44b4d14

**Comment by HpNoTiQ56** [comment]
As a hint, I've got confirmation than root is granted to process when it asks for it :
![image](https://github.com/user-attachments/assets/a59d0039-7327-48b5-9a67-1dc8333752e2)

**Comment by yuanwofei** [comment]
Try restarting your phone or reinstalling KernalSU (should solve the
problem)

HpNoTiQ ***@***.***> 于2024年11月11日周一 06:58写道：

**Comment by HpNoTiQ56** [comment]
Still not working I'm using sus_su enable to hide su !
![image](https://github.com/user-attachments/assets/951f2d9b-481e-48df-bdd3-4808c4c286e4)

**Comment by HpNoTiQ56** [comment]
Hi, could you tell me which path do you use to check root and which path your module needs to access?
I've added /vendor, /etc, /odm but no success so far. Can't even build KSU module.
![image](https://github.com/user-attachments/assets/2668b673-4b43-4bb0-852e-5c467d626dda)

**Comment by yuanwofei** [comment]
Using *SuperSu.rootAccess()* to check root. You can check the code in the
SuperSU.java file.


HpNoTiQ ***@***.***> 于2024年11月15日周五 05:38写道：

**Comment by HpNoTiQ56** [comment]
Hi,
Where do I find this SuperSU.java?
Do i need to extract your apk or find an example on GH? I've looked at superSU but it's kind of old.
You don't use this libs https://github.com/topjohnwu/libsu/tree/master/core/src/main to get root?
Moreover, some apps have a forceroot switch maybe it can be a way to overide susfs use?

**Comment by yuanwofei** [comment]
Please see the attached file

**Comment by HpNoTiQ56** [comment]
You forgot the file I think
